#!/usr/bin/env node
/* Rebuild the icon token block in index.html from the local SVG source files.
 *
 *   node tools/build-icons.mjs          rebuild
 *   node tools/build-icons.mjs --check  verify only, exit 1 if stale
 *
 * Sources: assets/icons/ and assets/figma-components/.
 * Operational icons are OUTLINE ONLY. Pixel-grid artwork (Nucleo Arcade and
 * anything else drawn as a field of square dots) is rejected, so a pixel icon
 * cannot re-enter the system by being dropped into the folder. GitHub is the
 * sole official brand-mark exception and remains a filled social glyph.
 *
 * Delivery: SVG CSS variables and currentColor are resolved, visible ink is
 * normalised to white with its alpha preserved, and the result is embedded as
 * a base64 data URI used as an alpha mask. That is what keeps the icons
 * rendering under file://, WebKit and srcdoc.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const HTML = join(ROOT, 'index.html')
const DIRS = ['assets/icons', 'assets/figma-components']
const START = '/* icon-tokens:start'
const END = '/* icon-tokens:end */'

/* filename -> token name, where the two differ */
const RENAME = { 'chart-bar': 'chart', dots: 'more' }
const BRAND_EXCEPTIONS = new Set(['github'])

/* ---------- collect ---------- */
const files = []
for (const dir of DIRS) {
  const abs = join(ROOT, dir)
  if (!existsSync(abs)) continue
  for (const f of readdirSync(abs).sort()) {
    if (f.endsWith('.svg')) files.push({ dir, file: f, path: join(abs, f) })
  }
}
if (!files.length) fail(`no SVGs found under ${DIRS.join(' or ')}`)

/* ---------- guard: outline only ---------- */
function assertOutline(svg, where, name) {
  // Arcade-style pixel grids are dozens of 1-unit dashes: d="M3 7H3.01"
  const dots = (svg.match(/d="M\s*[\d.]+\s+[\d.]+\s*H\s*[\d.]+\.0\d"/g) || []).length
  if (dots >= 12) {
    fail(
      `${where} is pixel-grid artwork (${dots} single-cell paths).\n` +
      `       The system is outline only — export the stroked family instead.`
    )
  }
  const strokes = (svg.match(/stroke="/g) || []).length
  const fills = (svg.match(/fill="(?!none)/g) || []).length
  if (strokes === 0 && fills > 0 && !BRAND_EXCEPTIONS.has(name)) {
    warn(`${where} has no strokes — looks like a solid/filled icon, not an outline one.`)
  }
}

/* ---------- normalise ink to white, keep alpha ---------- */
function toWhiteAlpha(svg) {
  return svg
    .replace(/<\?xml[^>]*\?>\s*/g, '')
    .replace(/<metadata>[\s\S]*?<\/metadata>\s*/g, '')
    .replace(/\s*<!--[\s\S]*?-->\s*/g, ' ')           // strip comments, keep one space
    .replace(/var\(--[^,)]+,\s*([^)]+)\)/g, '$1')      // var(--x, fallback) -> fallback
    .replace(/var\(--[^)]+\)/g, 'currentColor')        // var(--x) -> currentColor
    .replace(/(stroke|fill)="([^"]*)"/g, (m, prop, val) => {
      const v = val.trim()
      if (v === 'none' || v === 'transparent') return `${prop}="${v}"`
      const alpha = /^#[0-9a-f]{8}$/i.test(v) ? v.slice(7) : /^#[0-9a-f]{4}$/i.test(v) ? v[4].repeat(2) : ''
      return `${prop}="#FFFFFF${alpha.toUpperCase()}"`
    })
    .replace(/\s+/g, ' ')
    .trim()
}

const tokens = []
for (const { dir, file, path } of files) {
  const raw = readFileSync(path, 'utf8')
  const stem = basename(file, '.svg')
  const name = RENAME[stem] || stem
  assertOutline(raw, `${dir}/${file}`, name)
  if (tokens.some(t => t.name === name)) fail(`duplicate icon name "${name}" (${dir}/${file})`)
  tokens.push({ name, uri: Buffer.from(toWhiteAlpha(raw), 'utf8').toString('base64') })
}
tokens.sort((a, b) => a.name.localeCompare(b.name))

/* ---------- render the block ---------- */
const block = [
  `${START} — generated by tools/build-icons.mjs, do not hand-edit */`,
  '/* Icon tokens. One outline family, plus the GitHub brand exception, delivered as white-alpha data-URI masks.',
  '   Regenerate after dropping new SVGs into assets/icons/ or assets/figma-components/:',
  '     node tools/build-icons.mjs',
  '   The builder refuses pixel-grid artwork, so the outline family cannot regress. */',
  ':root{',
  ...tokens.map(t => `  --ico-${t.name}:url("data:image/svg+xml;base64,${t.uri}");`),
  '}',
  tokens.map(t => `.icon-${t.name}{--icon:var(--ico-${t.name})}`).join(''),
  END,
].join('\n')

const html = readFileSync(HTML, 'utf8')
const from = html.indexOf(START)
const to = html.indexOf(END)
if (from < 0 || to < 0) fail(`could not find the ${START} … ${END} markers in index.html`)
const next = html.slice(0, from) + block + html.slice(to + END.length)

if (process.argv.includes('--check')) {
  if (next !== html) fail('icon tokens are stale — run: node tools/build-icons.mjs')
  console.log(`icon tokens up to date (${tokens.length} icons; operational set is outline-only)`)
} else {
  writeFileSync(HTML, next)
  console.log(`wrote ${tokens.length} icon tokens: ${tokens.map(t => t.name).join(', ')}`)
}

function fail(msg) { console.error(`build-icons: ${msg}`); process.exit(1) }
function warn(msg) { console.warn(`build-icons: warning — ${msg}`) }
